apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      nodePort: 81
      port: 8888
      targetPort: 8888
