apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil42
  name: wil42
spec:
  ports:
  - name: wil42
    nodePort: 30080
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil42
  type: NodePort
